#!/bin/bash

function localread() {
  L_LABEL=$1
  L_DEFAULT=$2
  L_VAR=$3
  L_ADDITIONAL=$4

  if [ -z "${!L_VAR}" ];
  then
    read "-${L_ADDITIONAL}rep" "${L_LABEL} " -i "${L_DEFAULT}" "${L_VAR}"
  fi
}

function requestKey() {
    keyType=$1
    echo '=> Preparing Repo'
    echo '=> Create Branch with Username and Unix Timestamp'
    BRANCH="request/$keyType/$(echo "$GIT_USER_NAME" | tr -d " \t\r")/$(date +%s)"
    git checkout -b "$BRANCH"

    echo "=> Generating $keyType key"
    tuf gen-key --expires=548 "$keyType"

    read -rp "=> You are requesting a ${keyType} to ${BRANCH} is this correct? (y/N): " USERCONFIRM

    if [[ $USERCONFIRM = "y" || $USERCONFIRM = "Y" ]]; then
      echo '=> Adding staged request'
      git add staged/

      echo '=> Comminting request'

      git commit -m "@${GIT_USER_NAME} requesting root key"

      echo '=> Pusing changes'
      git push --set-upstream origin "$BRANCH"

      echo '=> Request submitted! - Exit'
      echo '------------------------------'
      exit 0

      else
        echo '=> Cancle request - Ressting'
        git checkout .
        git reset --hard
        git clean -fd
        echo '=> Exit'
        exit 1
    fi
}

echo '=> Which Role Key would you like to generate?'

echo '=> [1] root'
echo '=> [2] timestamp'
echo '=> [3] snapshot'
echo '=> [4] targets'
localread "Key type to request:" "" KEY_OPTION


declare -A KEY_OPTIONS=( [1]=root [2]=timestamp [3]=snapshot [4]=targets )

for key in "${!KEY_OPTIONS[@]}"; do
  if [ "$key" == "$KEY_OPTION" ]; then
    KEY_OPTION=${KEY_OPTIONS[$key]};
  fi
done

if [[ $KEY_OPTION = "root" ]]; then
    echo '=> Creating new root key'
    requestKey "$KEY_OPTION"
elif [[ $KEY_OPTION = "timestamp" ]]; then
    echo '=> Creating new timestamp key'
    requestKey "$KEY_OPTION"
elif [[ $KEY_OPTION = "snapshot" ]]; then
    echo '=> Creating new snapshot key'
    requestKey "$KEY_OPTION"
elif [[ $KEY_OPTION = "targets" ]]; then
    echo '=> Creating new targets key'
    requestKey "$KEY_OPTION"
else
    echo '=> Wrong input - Exit'
    exit 1
fi
